### ISSUE TITLE
Undefined reference to `stdscr' while using ncurses

### ISSUE THREAD

**Issue by ghost** [eriksvedang/carp-ncurses#15]
Carp version: v0.5.5

Hello.

On OpenSUSE LEAP 15.3, I failed to build `examples/example.carp` due to the error in the title. Apparently, `stdscr` is not part of my libncurses package and is part of libtinfo. 

I fixed it by adding `(add-lib '-ltinfo')` into ncurses.carp file. So, I wonder if it's a good idea to add the piece of code to the upstream library or mention it in troubleshooting/usage instructions?

**Comment by scolsen** [comment]
Thanks for reporting, and for the fix! That's interesting, but not too surprising, I believe various curses implementations handle certain things differently--I'll have to dig through the ncurses archives to see if there's a documented reason for this.

In the meantime, I don't think linking in tinfo would have any adverse effects, so that seems ok with me.

**Comment by eriksvedang** [comment]
Let's go for it!

**Comment by ghost** [comment]
Alright :slightly_smiling_face:. I'll send a PR with the change.
